MODE_ADMIN: 0x00
MODE_AUTH: 0x01
MODE_SIGN: 0x02

INS_GET_STATUS: 0xA0
INS_GENERATE_KEYPAIR: 0xA1
INS_GET_PUBLIC_KEY: 0xA2
INS_GET_PRIVATE_KEY: 0xA3
INS_GET_CERTIFICATE: 0xA4
INS_SET_CERTIFICATE: 0xA5
INS_CREATE_SIGNATURE: 0xA6
INS_VERIFY_PIN: 0xB1
INS_PIN_RETRIES_LEFT: 0xB2
INS_CHANGE_PIN: 0xB3
INS_SET_PIN: 0xB4

OQS_SIG_alg_dilithium_2: 0xD2
OQS_SIG_alg_dilithium_3: 0xD3
OQS_SIG_alg_dilithium_5: 0xD5
OQS_SIG_alg_falcon_512: 0xF0
OQS_SIG_alg_falcon_1024: 0xF1
OQS_SIG_alg_sphincs_sha256_128s_simple: 0x51
OQS_SIG_alg_sphincs_sha256_128f_simple: 0x52
OQS_SIG_alg_sphincs_sha256_192s_simple: 0x53
OQS_SIG_alg_sphincs_sha256_192f_simple: 0x54
OQS_SIG_alg_sphincs_sha256_256s_simple: 0x55
OQS_SIG_alg_sphincs_sha256_256f_simple: 0x56
OQS_SIG_alg_sphincs_haraka_256s_simple: 0x65

STATUS_WORDS:
  0x9000: "SW_SUCCESS"
  0x6F00: "SW_INTERNAL_ERROR"
  0x6701: "SW_WRONG_LENGTH_CONTAINED"
  0x6702: "SW_WRONG_LENGTH_EXPECTED"
  0x6703: "SW_WRONG_MODE"
  0x6704: "SW_WRONG_ALGORITHM"
  0x6705: "SW_WRONG_DATA"
  0x6D00: "SW_INS_NOT_SUPPORTED"
  0x9400: "SW_FILE_ERROR"
  0x6982: "SW_SECURITY_STATUS_NOT_SATISFIED"
  0x63C0: "SW_WRONG_PIN_X_TRIES_LEFT"
  0x6301: "SW_PIN_VERIFICATION_REQUIRED"
  0x9700: "SW_PIN_BLOCKED"
