#ifndef SUPPORTED_STATUS_WORDS_H
#define SUPPORTED_STATUS_WORDS_H

// Status words (most of these values are inherited from SmartCard+Web-eID specifications)
enum SW {
    SW_SUCCESS = 0x9000,
    SW_INTERNAL_ERROR = 0x6F00,
    SW_WRONG_LENGTH_CONTAINED = 0x6701,
    SW_WRONG_LENGTH_EXPECTED = 0x6702,
    SW_WRONG_MODE = 0x6703,
    SW_WRONG_ALGORITHM = 0x6704,
    SW_WRONG_DATA = 0x6705,
    SW_INSTRUCTION_NOT_ALLOWED = 0x6D00,
    SW_FILE_ERROR = 0x9400,
    SW_SECURITY_STATUS_NOT_SATISFIED = 0x6982,
    SW_WRONG_PIN_X_TRIES_LEFT = 0x63C0,
    SW_PIN_VERIFICATION_REQUIRED = 0x6301,
    SW_PIN_BLOCKED = 0x9700,
};

#endif
